name: car_makeover_studio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  auto_route: ^5.0.4
  avatar_glow: ^2.0.2
  camera: ^0.10.3+2
  carousel_slider: ^4.2.1
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.9
  custom_radio_grouped_button: ^2.1.2+2
  dartz: ^0.10.1
  day_night_switcher: ^0.2.0+1
  device_info_plus: ^8.1.0
  dio: ^5.1.1
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  file_picker: ^5.2.6
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  flutter_adaptive_ui: ^0.8.0+1
  flutter_bloc: ^8.1.2
  flutter_conditional_rendering: ^2.0.0
  flutter_image_map: ^0.9.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_secure_storage: ^8.0.0
  flutter_staggered_grid_view: ^0.6.2
  form_field_validator: ^1.1.0
  full_screen_image: ^2.0.0
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  google_mlkit_text_recognition: ^0.5.0
  group_button: ^5.2.2
  hive: ^2.2.3
  image_picker: ^0.8.7
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  mask_text_input_formatter: ^2.4.0
  multiple_result: ^4.0.0
  path_provider: ^2.0.13
  signature: ^5.3.2
  slide_countdown: ^0.5.0
  url_strategy: ^0.2.0
dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_flavorizr: ^2.1.6
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.4

  json_serializable: ^6.6.1
  lints: ^2.0.1
dependency_overrides:
  intl: ^0.17.0
flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  localizely:
    project_id: "286"
flutter_native_splash:
  image: assets/png/app_icon.png
  color: "1C1B1F"
flavorizr:
  flavors:
    production:
      app:
        name: "Car Makeover Studio"
      android:
        applicationId: "com.carmakeoverstudio.carmakeoverstudio"
      ios:
        bundleId: "com.carmakeoverstudio.carmakeoverstudio"
    staging:
      app:
        name: "Car Makeover Studio"
      android:
        applicationId: "com.carmakeoverstudio.carmakeoverstudio.staging"
      ios:
        bundleId: "com.carmakeoverstudio.carmakeoverstudio.staging"
    development:
      app:
        name: "Car Makeover Studio"
      android:
        applicationId: "com.carmakeoverstudio.carmakeoverstudio.dev"
      ios:
        bundleId: "com.carmakeoverstudio.carmakeoverstudio.dev"
